### ISSUE TITLE
Allow get put and post for other Schema Descriptors

### ISSUE THREAD

**Issue by benedikt-buchert** [pitchmuc/aepp#1]
Thanks a lot again for your work on this!

Currently extend a soft enum field for event types is only possible via API so being able to update other Schema Descriptors would help to do this.

[Extend a soft enum field](https://experienceleague.adobe.com/docs/experience-platform/xdm/tutorials/extend-soft-enum.html?lang=en)

I did not manage to do this with the current Python wrapper? Can you help here?

**Comment by pitchmuc** [comment]
I never worked on this but as I am doing a massive upgrade on aepp (and discovering some issues) I will add that capability in the next release.

**Comment by pitchmuc** [comment]
Release on 0.2.6 (now available on pypi)
