### ISSUE TITLE
Error handling in `getSchemas`

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#10]
Right now if you call `getSchemas` but there is some authentication issue, it fails with some intermediate stack trace that obfsucates what is happening.

**Comment by pitchmuc** [comment]
Hello Charles, 
Can you provide the error in description ?

**Comment by pitchmuc** [comment]
I am hopefully improving this in the next release.

**Comment by pitchmuc** [comment]
Improved with 0.2.9
