### ISSUE TITLE
Add support for triggering dataset export in destinatons

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#12]
This functionality is being built internally right now, and once it is available we would like to update the `destination` module to trigger on-demand dataset exports. 

Right now the call to create a destination just takes a raw dictionary `destinationObj: dict` but it would be nice to actually be able to programmatically pass just a `dataset_id: str` and not having to deal with complicated payloads.

**Comment by pitchmuc** [comment]
Assigning this to you @cmenguy as you seem to know this new functionality. 
If you can not amend this and wish for me to take over, we will need to wait till documentation is available on that feature. 
I do not have access to beta feature (yet).
