### ISSUE TITLE
Patching datasets seems to have invalid content type

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#15]
Trying to enable a dataset for profile ingestion with `enableDatasetProfile` in `catalog.py` is failing due to invalid content type:

```
Out[248]: {'type': '/placeholder/type/uri', 'status': 400, 'title': 'BadRequestError', 'detail': 'Content-type does not match json-patch body format, value of Content-type should be application/json-patch+json.'}
```

**Comment by pitchmuc** [comment]
Thanks for that. 
I was just following the documentation: <https://developer.adobe.com/experience-platform-apis/references/catalog/#tag/Datasets/operation/patchDataset>
Apparently the documetnation is not correct

**Comment by pitchmuc** [comment]
Hopefully fixed with latest release. 
As documentation is not correct to begin with, I hope it is really fixed now.
