### ISSUE TITLE
Support data landing zone

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#17]
It would be useful to support the API calls to the data landing zone (DLZ) so users can retrieve their blob container and credentials.

Details on API under https://experienceleague.adobe.com/docs/experience-platform/sources/api-tutorials/create/cloud-storage/data-landing-zone.html?lang=en

**Comment by pitchmuc** [comment]
Definitely coming in the next release

**Comment by pitchmuc** [comment]
I have added the different functionalities presented in your link. 
However, I feel we are still missing some steps and the official documentation is incomplete. 
The information has been added in the last commit. I am close to completion for release of new version of aepp on wednesday.

**Comment by pitchmuc** [comment]
Closing for now, if we miss anything, I can add more methods in the future. 
Release on 0.2.6 (now available on pypi)
