### ISSUE TITLE
Batch data ingestion of a json file - `uploadSmallFile`

### ISSUE THREAD

**Issue by Ashika08** [pitchmuc/aepp#26]
**Current**:
The `uploadSmallFile` currently takes a python dictionary as the input for data to be ingested. 

**Suggested**:
To add an additional parameter - `localFilePath` that takes the path of the json file and uses `json.load()` to read the file into a dictionary. Basically, to handle the file processing part by the wrapper.

**Comment by pitchmuc** [comment]
Thanks for the proposal. This has been handled by the afdeec4 commit
