### ISSUE TITLE
Accept schema ID for enabling Schema for Real Time

### ISSUE THREAD

**Issue by Ashika08** [pitchmuc/aepp#29]
The method - `enableSchemaForRealTime` in the schema module, currently only accepts `meta:altId` attribute for a schema. The method does not support the `$id` attribute  at the moment. 

It could be enhanced to accept either - `meta:altId` or `$id` for enabling a schema for RT.

**Comment by pitchmuc** [comment]
Hello @Ashika08, 
Sorry for the delay, this will be release in the next iteration. `0.3.2` 
Thanks for tip
