### ISSUE TITLE
Calling Catalog.enableDatasetProfile doesn't seem to do anything

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#42]
The call to `enableDatasetProfile` seems to succeed, but it also seems to have no effect on the dataset, and I've verified on multiple occasions the "Profile" toggle is not flipped on even after this. Seems like some kind of bug, I haven't looked at the root cause.

**Comment by pitchmuc** [comment]
I think I found the issue it was a space within the setup. 
It has been fixed during one of the latest release. 
Closing this, feel free to re-open if still issue after upgrading to the latest version
