### ISSUE TITLE
Error in retrieving datasets

### ISSUE THREAD

**Issue by naynikaw** [pitchmuc/aepp#48]
### Expected Behaviour
Expected behaviour is to get dataset labels on invoking the datasets.Datasets() method. I have added the config correctly as the Schemas module is working fine.

### Actual Behaviour
seeing this error:
AttributeError: module 'aepp.datasets' has no attribute 'Datasets'

![image](https://user-images.githubusercontent.com/42168952/236743302-a722ccac-41f4-40d2-a98d-b91078f26384.png)
On invoking the help method I see the class Datasets. Not sure what I'm doing wrong.
![image](https://user-images.githubusercontent.com/42168952/236744154-139db4b3-a4ca-454f-8dbb-67e4696e9a09.png)

**Comment by pitchmuc** [comment]
Hello, 

You will need to pass a configuration file before instantiating the DataSet class. 
I would recommend you to go through the `get-started` documentation : <https://github.com/pitchmuc/aepp/blob/main/docs/getting-started.md>
