### ISSUE TITLE
Profile and Identity enabled is not properly passed in createDataSets

### ISSUE THREAD

**Issue by gurcan-ibmix** [pitchmuc/aepp#56]
### Expected Behaviour
While creating a new datasets, profile and identity are enabled.

### Actual Behaviour
While creating a new datasets, profile and identity are not enabled. 

### Reproduce Scenario (including but not limited to)
While calling createDataSets I'm sending **profileEnabled=True, identityEnabled=True** 
But in the UI I see that it's not enabled.
#### Sample Code that illustrates the problem
`connection.createDataSets(name=name, schemaId=schema_id, profileEnabled=True, identityEnabled=True)`
In **catalog.py**  following part causing the issue:
```
if profileEnabled:
  data['tags']["unifiedProfile"] = ["enabled: true"]
if identityEnabled:
  data['tags']["unifiedIdentity"] = ["enabled: true"]`
```
There shouldn't be any space in **enabled: true**

I created the following object
```
tags = {
        "unifiedProfile": [
            "enabled:true"
        ],
        "unifiedIdentity": [
            "enabled:true"
        ]
    }

```
Then passed as a parameter to createDataSets and verified in the UI that they are enabled
`connection.createDataSets(name=name, schemaId=schema_id, tags=tags )`

**Comment by pitchmuc** [comment]
Thanks for pointing out that problem/typo and cool that you were able to bypassed that via the provided parameters. 
Happy the flexibility of the module helped you in that regards. 
Sorry for the delay on this, at the moment, the support is limited on this module. 
I will release a new version of the module where you do not need to use the tags element.

**Comment by pitchmuc** [comment]
release with version `0.3.1.post7`
