### ISSUE TITLE
Passing the sandbox programmatically

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#6]
Currently to pass the sandbox the documentation mentions using `kwargs` to pass it like this:

```
mySchemaConnection1 = schema.Schema({"x-sandbox-name":"mySandbox1"})
```

However in the orgs I have tried this on it gives an error about having an invalid source, even when just using the default `prod` sandbox. I can only get this to work when not passing the sandbox at all so it defaults to the default sandbox.

We would like to add the following:
- Ability to pass the sandbox as a full-fledged parameter so you could do for example `schema.Schema(sandbox_name=foo)`
- Error handling to provide more details why the source is not working

**Comment by pitchmuc** [comment]
FYI : I am working on this, should be fairly easily, there will be 2 way to achieve that in the future. 
passing a `sandbox` parameter during instanciation or passing different `ConnectObject` instances for each instanciation. 
The ConnectObject class is something I wanted to do for a long time, it is that when you configure your aepp, you can return an instance of a class that keep the information in memory. 
You can then pass that instance in each of your other class instantiation.

**Comment by pitchmuc** [comment]
Release on 0.2.6 (now available on pypi)
