### ISSUE TITLE
Support service tokens

### ISSUE THREAD

**Issue by cmenguy** [pitchmuc/aepp#9]
Currently the library is very much tailored to JWT-based authentication.

However it would be really useful to also support service tokens where you just have a client ID, client secret and auth code. This would allow this library to be used directly in services, and some APIs are also only accessible via service tokens.

**Comment by pitchmuc** [comment]
Can you provide the type of header that is used when accessing the API endpoint with Service Token ? \
I am wondering if that is not just to support the assignment of a specific token during instantiation.
However, in that case, a native token regeneration built on top of JWT and included in the library should not be activated when the token expires.

**Comment by cmenguy** [comment]
It's not so much different header, but actually a different IMS endpoint and using a permanent auth code that is generated for services.
